picBaseUrl: "http://host.docker.internal:5202/c/api/v1/catalog/items/[0]/pic/"
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
    io.r2dbc.r2dbc-mssql: DEBUG
    io.r2dbc.r2dbc-mssql.PARAM: DEBUG